### ISSUE TITLE
After the server encountered an error, the tps dropped entirely

### ISSUE THREAD

**Issue by 347180440** [killerprojecte/Folia#11]
### Stack trace

[17:50:33 ERROR]: Attempting to read chunk data at [26, 36] but got chunk data for [26, 37] instead! Attempting regionfile recalculation for regionfile F:\ArNetWork\1.19.4\.\world_nether\DIM-1\region\r.0.1.mca
[17:50:33 WARN]: Corrupt regionfile header detected! Attempting to re-calculate header offsets for regionfile F:\ArNetWork\1.19.4\.\world_nether\DIM-1\region\r.0.1.mca
java.lang.Throwable: null
        at net.minecraft.world.level.chunk.storage.RegionFile.recalculateHeader(RegionFile.java:142) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"]
        at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:257) ~[?:?]
        at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:230) ~[?:?]
        at net.minecraft.world.level.chunk.storage.ChunkStorage.readSync(ChunkStorage.java:176) ~[?:?]
        at net.minecraft.server.level.ChunkMap.readSync(ChunkMap.java:798) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"]
        at net.minecraft.server.level.ServerLevel$1.readData(ServerLevel.java:364) ~[?:?]
        at io.papermc.paper.chunk.system.io.RegionFileIOThread$ChunkDataTask.run(RegionFileIOThread.java:1260) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"]
        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue$PrioritisedTask.executeInternal(PrioritisedThreadedTaskQueue.java:351) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"]
        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue.executeTask(PrioritisedThreadedTaskQueue.java:118) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"]
        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.pollTasks(PrioritisedQueueExecutorThread.java:110) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"]
        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:50) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"]

### Plugin and Datapack List

[18:20:53 INFO]: Bukkit Plugins:
[18:20:53 INFO]:  - ajLeaderboards, AntiCropTrampleFolia, argt, ArtMap, AtLite, Ball, BlockLocker, Cgifts, Chat2QQ
[18:20:53 INFO]:  ChatColor2, *ChatTPA, CoreProtect, cupbot, CustomJoinAndQuitMessages, DecentHolograms, DraconyxPro, *EasyCommand, Essentials, EssentialsSpawn
[18:20:53 INFO]:  EzChestShop, FartherViewDistance, FoliaFlow, ghome, GSit, HavenPack, InvSeePlusPlus, InvSeePlusPlus_Clear, InvSeePlusPlus_Give, Ip2region
[18:20:53 INFO]:  jext, LibsDisguises, LinearBot, LiteItemShow, *LiveRecorder, LuckPerms, MessageOverHead, MinesweeperMC, MiraiMC, Morphy
[18:20:53 INFO]:  PlaceholderAPI, Plan, PlayerGuild, PlayerTop, PlugMan, PowerBoard, ProtocolLib, RayTraceAntiXray, Skulls, SuperVanish
[18:20:53 INFO]:  TAB, ValorlessUtils, Vault, ViaBackwards, ViaRewind, ViaVersion, vilib, Vivecraft-Spigot-Extensions, Whitelist4QQ, WorldEdit

### Actions to reproduce (if known)

> tps
[18:01:00 INFO]: Server Health Report
 - Online Players: 17
 - Total regions: 15
 - Utilisation: 232.1% / 1,600.0%
 - Load rate: 1.47, Gen rate: 0.00
 - Lowest Region TPS: 6.71
 - Median Region TPS: 7.18
 - Highest Region TPS: 7.22
Highest 3 utilisation regions
 - Region around block [w:'world',-329,80,-873]:
    43.3% util at 66.31 MSPT at 6.71 TPS
    Chunks: 15 Players: 1 Entities: 3,078
 - Region around block [w:'world',-4361,80,-5257]:
    41.8% util at 57.59 MSPT at 7.22 TPS
    Chunks: 380 Players: 2 Entities: 821
 - Region around block [w:'world',2183,80,-4121]:
    41.1% util at 56.75 MSPT at 7.22 TPS
    Chunks: 220 Players: 1 Entities: 1,252

### Folia version

> version
[18:21:18 INFO]: Checking version, please wait...
[18:21:19 INFO]: This server is running DirtyFolia version git-DirtyFolia-"5625b94" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 5625b94 on ver/1.20)
You are running the latest version
Previous version: git-Purpur-2022 (MC: 1.20.1)

**Comment by killerprojecte** [comment]
Caused by Minecraft, Report to PaperMC not me
